### ISSUE TITLE
REPL parsing fails sometimes

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#618]
When issue a command like:

```
R> :slicer -c "2@x" -r "x <- 3 * 4\n y <- x * 2"
```

The argument parser seems to get tripped up by the `<-`. We should make it work with `;` and `<-`!

**Comment by bjthehun** [comment]
Actually, the problems seems to come from how flowR currently splits user input with `splitAtEscapeSensitive`.

Split 1, in `replProcessAnswer` within `src/cli/repl/core.ts`, produces the statement:
```
[
	":slicer -c 2@x -r x <- 3 * 4\n y <- x * 2"
]
```

Here, the quotation marks surrounding the statement have been removed. From the current test cases, this seems to be the intended result.
Split 2, in lines 71-87 of `src/cli/repl/commands/commands.ts`, then produces the following arguments from `-c 2@x -r x <- 3 * 4\n y <- x * 2`:

```
[
  "-c",
  "2@x",
  "-r",
  "x",
  "<-",
  "3",
  "*",
  "4\n",
  "y",
  "<-",
  "x",
  "*",
  "2",
]
```

Because of the missing quotation marks, `splitAtEscapeSensitive` sees `x`, `<-`, `3` etc. as arguments, too. When I manually added back the quotation marks to the result of Split 1, the slicer command succeeded.
So, for splitting statements, flowR should probably leave in quotation marks.
