### ISSUE TITLE
Post Modularization-Issues

### ISSUE THREAD

**Issue by bjthehun** [Code-Inspect/flowr#739]
![Bildschirmfoto vom 2024-03-21 15-38-09](https://github.com/Code-Inspect/flowr/assets/38729215/dccb0eee-33fd-43d2-a52d-536a12f7c621)

![Bildschirmfoto vom 2024-03-21 15-39-21](https://github.com/Code-Inspect/flowr/assets/38729215/bc0e1902-65e5-44a3-8096-afde04294fe2)

As follow-up to #716, linting and testing for the `benchmark` and `cli` modules appear to not work.

**Comment by Ellpeck** [comment]
This is intentional, as the next step of the modularization will be moving the linting out to its own repository (#699) and then moving these modules into their own repositories as well. The former will save us having to copy around all of the linting rules especially, including between this repository, the extension repository, and others :)

**Comment by EagleoutIce** [comment]
Partially dealt with in #741.
