### ISSUE TITLE
Checking expected output for tests doesn't seem to cause the shell to be cleaned up

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#807]
Specifically, running a test like

```ts
		assertSliced(label('redefine if', ['name-escaped', ...OperatorDatabase['<-'].capabilities, 'numbers', 'formals-dot-dot-dot', 'newlines', 'unnamed-arguments']),
			shell, `\`if\` <- function(...) 2
if(1) 
   x <- 3
print(x)`, ['4@x'], 'x <- 3\nx', { expectedOutput: '[1] 2' })
```

causes future tests to fail, even tests without an expected output, indicating that it causes the shell to choke somehow.

**Comment by EagleoutIce** [comment]
This is solely related to the fact that the code does not have `x` in the given example and requires the previous `x <- 1` definition, otherwise it is syntactically incorrect. Wen can do a separate issue (open it if you want to) which improves `expectedOutputs` error handling in general. I transform this issue to another one: the expected slice is wrong and should be `x <- 1` (or whatever is defined before) as `x <- 3` is not active.

**Comment by EagleoutIce** [comment]
Part of #98.
