### ISSUE TITLE
Inconsistencies when reconstructing with closures

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#821]
Specifically, these two tests produce (seemingly) unexpected results.

The first test's reconstruction doesn't include the implicit return value of `f`, which I'm not 100% sure is an error:
```ts
		assertSliced(label('nested closures w/ default arguments', ['name-normal', ...OperatorDatabase['<-'].capabilities, 'formals-default', 'numbers', 'newlines', 'lambda-syntax', 'implicit-return', ...OperatorDatabase['+'].capabilities, 'closures', 'grouping']),
			shell, `f <- function(x = 1) {
  (\\(y = 2) function(z = 3) x + y + z)()
}
g <- f(8)
print(g())`, ['5@g'], `f <- function(x=1) {} 
g <- f(8)
g()`)
```

The second test's reconstruction only calls `f` once, meaning `x`'s new value will never actually be set.
```ts
		assertSliced(label('closure w/ side effects', ['name-normal', ...OperatorDatabase['<-'].capabilities, 'normal-definition', 'newlines', 'closures', ...OperatorDatabase['<<-'].capabilities, 'side-effects-in-function-call', ...OperatorDatabase['+'].capabilities, 'numbers']),
			shell, `f <- function() {
  function() {
    x <<- x + 1
    x
  }
}
x <- 2
f()()
print(x)`, ['9@x'], `f <- function() { function() x <<- x + 1 }
x <- 2
f()
x`)
```

**Comment by EagleoutIce** [comment]
This was caused by two independent errors.
The first one was due to unnamed function calls linking the body as entry point, and not the call itself, leading to the df-graph being incapable of detecting that the implicit return of the function (i.e., the inner lambda with `\`) is actually called. 
The second one was an old and outdated guard in the reconstruction which just plainly prevented two `()` from being set right after each other.

**Comment by EagleoutIce** [comment]
The test-updates should happen in #800.
